---
# tasks file for k8s_pre

- name: Install prerequisites for Docker repository
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2', 'software-properties-common']
    update_cache: yes

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    # deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable

- name: Install Docker CE
  apt:
    name: ['docker-ce=5:19.03.15~3-0~ubuntu-bionic', 'docker-ce-cli=5:19.03.15~3-0~ubuntu-bionic', 'containerd.io=1.3.9-1']
    update_cache: yes


- name: Create "docker" group
  group:
    name: "docker"
    state: present

- name: Add remote "ubuntu" user to "docker" group
  user:
    name: "ubuntu"
    group: "docker"
    append: yes


- name: Apply sysctl settings
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    sysctl_set: yes # try whithout

- name: Disable swap
  command: swapoff -a

# test this
- name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

# sudo groupadd docker
- name: Create "docker" group
  group:
    name: docker
    state: present

# sudo usermod -aG docker root
- name: Add remote "ubuntu" user to "docker" group
  user:
    name: vagrant
    group: docker
    append: yes